interface Coffee {
  rating: number;
  name: string;
  roast: string;
  origin: string;
  filename: string;
  notes: string[];
  price: number;
  weight: number;
}

export const Coffees: Coffee[] = [
  { name: "Arabica", price: 23.5, rating: 9, weight: 25, filename: "arabica-dark-guatemala.png", origin: "Guatemala", roast: "dark", notes: ["Cocoa", "Sage", "Orange blossom"] },
  { name: "Robusta", price: 21.0, rating: 7, weight: 25, filename: "robusta-medium-uganda.png", origin: "Uganda", roast: "medium", notes: ["Clove", "Vanilla"] },
  {
    name: "Bourbon",
    price: 23.04,
    rating: 3,
    weight: 18,
    filename: "bourbon-medium-tanzania.png",
    origin: "Tanzania",
    roast: "medium",
    notes: ["Dark chocolate", "Plum", "Maple syrup"],
  },
  { name: "Typica", price: 22.0, rating: 10, weight: 25, filename: "typica-light-brazil.png", origin: "Brazil", roast: "light", notes: ["Cardamom", "Vanilla", "Jasmine"] },
  { name: "Geisha", price: 14.3, rating: 4, weight: 11, filename: "geisha-light-colombia.png", origin: "Colombia", roast: "light", notes: ["Maple syrup", "Woody"] },
  { name: "Catuai", price: 14.72, rating: 4, weight: 16, filename: "catuai-light-indonesia.png", origin: "Indonesia", roast: "light", notes: ["Apple", "Vanilla"] },
  { name: "SL28", price: 7.56, rating: 4, weight: 6, filename: "sl28-light-yemen.png", origin: "Yemen", roast: "light", notes: ["Clove", "Rose", "Vanilla"] },
  { name: "SL34", price: 20.32, rating: 7, weight: 16, filename: "sl34-light-indonesia.png", origin: "Indonesia", roast: "light", notes: ["Raisin", "Apricot", "Cashew"] },
  { name: "Pacamara", price: 24.42, rating: 7, weight: 22, filename: "pacamara-medium-honduras.png", origin: "Honduras", roast: "medium", notes: ["Cocoa", "Apricot", "Hazelnut"] },
  { name: "Maragogipe", price: 30.0, rating: 2, weight: 25, filename: "maragogipe-dark-tanzania.png", origin: "Tanzania", roast: "dark", notes: ["Lavender", "Berry"] },
  { name: "Caturra", price: 8.36, rating: 2, weight: 11, filename: "caturra-light-yemen.png", origin: "Yemen", roast: "light", notes: ["Malt", "Plum", "Orange blossom"] },
  { name: "Castillo", price: 22.32, rating: 2, weight: 18, filename: "castillo-medium-kenya.png", origin: "Kenya", roast: "medium", notes: ["Cherry", "Jasmine", "Mint"] },
  { name: "Catimor", price: 7.5, rating: 4, weight: 6, filename: "catimor-medium-costa-rica.png", origin: "Costa Rica", roast: "medium", notes: ["Walnut", "Earthy"] },
  { name: "Ruiru 11", price: 4.44, rating: 5, weight: 6, filename: "ruiru-11-light-colombia.png", origin: "Colombia", roast: "light", notes: ["Mint", "Malt", "Berry"] },
  { name: "Villalobos", price: 16.38, rating: 2, weight: 18, filename: "villalobos-light-colombia.png", origin: "Colombia", roast: "light", notes: ["Mint", "Smoky", "Vanilla"] },
  { name: "Mokka", price: 38.5, rating: 6, weight: 25, filename: "mokka-medium-honduras.png", origin: "Honduras", roast: "medium", notes: ["Earthy", "Caramel", "Apricot"] },
  {
    name: "Mundo Novo",
    price: 11.84,
    rating: 10,
    weight: 16,
    filename: "mundo-novo-medium-vietnam.png",
    origin: "Vietnam",
    roast: "medium",
    notes: ["Orange blossom", "Earthy", "Cinnamon"],
  },
  {
    name: "Blue Mountain",
    price: 23.98,
    rating: 4,
    weight: 22,
    filename: "blue-mountain-dark-guatemala.png",
    origin: "Guatemala",
    roast: "dark",
    notes: ["Orange blossom", "Hibiscus"],
  },
  { name: "Kona", price: 25.75, rating: 6, weight: 25, filename: "kona-dark-vietnam.png", origin: "Vietnam", roast: "dark", notes: ["Cardamom", "Maple syrup"] },
  { name: "Laurina", price: 12.6, rating: 10, weight: 18, filename: "laurina-light-vietnam.png", origin: "Vietnam", roast: "light", notes: ["Citrus", "Cinnamon"] },
  { name: "Obata", price: 10.23, rating: 2, weight: 11, filename: "obata-dark-guatemala.png", origin: "Guatemala", roast: "dark", notes: ["Nutmeg", "Earthy", "Clove"] },
  { name: "Icatu", price: 15.68, rating: 3, weight: 16, filename: "icatu-dark-indonesia.png", origin: "Indonesia", roast: "dark", notes: ["Thyme", "Hibiscus", "Dark chocolate"] },
  { name: "San Ramon", price: 5.46, rating: 3, weight: 7, filename: "san-ramon-medium-indonesia.png", origin: "Indonesia", roast: "medium", notes: ["Tobacco", "Thyme", "Nutmeg"] },
  { name: "Pache", price: 11.88, rating: 10, weight: 18, filename: "pache-light-india.png", origin: "India", roast: "light", notes: ["Citrus", "Berry", "Smoky"] },
  { name: "Sarchimor", price: 35.5, rating: 3, weight: 25, filename: "sarchimor-dark-brazil.png", origin: "Brazil", roast: "dark", notes: ["Smoky", "Thyme"] },
  { name: "Amarello", price: 7.08, rating: 6, weight: 6, filename: "amarello-medium-kenya.png", origin: "Kenya", roast: "medium", notes: ["Lavender", "Jasmine"] },
  {
    name: "Bourbon Pointu",
    price: 14.4,
    rating: 4,
    weight: 32,
    filename: "bourbon-pointu-dark-guatemala.png",
    origin: "Guatemala",
    roast: "dark",
    notes: ["Berry", "Hibiscus", "Clove"],
  },
  { name: "Orange Bourbon", price: 17.92, rating: 8, weight: 32, filename: "orange-bourbon-light-peru.png", origin: "Peru", roast: "light", notes: ["Apple", "Lavender", "Apricot"] },
  { name: "Jackson", price: 21.76, rating: 2, weight: 32, filename: "jackson-medium-peru.png", origin: "Peru", roast: "medium", notes: ["Plum", "Hibiscus", "Woody"] },
  { name: "Batian", price: 4.95, rating: 7, weight: 11, filename: "batian-light-uganda.png", origin: "Uganda", roast: "light", notes: ["Walnut", "Tobacco"] },
  {
    name: "Yellow Bourbon",
    price: 26.4,
    rating: 4,
    weight: 22,
    filename: "yellow-bourbon-dark-kenya.png",
    origin: "Kenya",
    roast: "dark",
    notes: ["Milk chocolate", "Peach", "Cocoa"],
  },
  {
    name: "Pink Bourbon",
    price: 11.13,
    rating: 9,
    weight: 7,
    filename: "pink-bourbon-dark-vietnam.png",
    origin: "Vietnam",
    roast: "dark",
    notes: ["Cinnamon", "Dark chocolate", "Tobacco"],
  },
  { name: "K7", price: 5.58, rating: 5, weight: 6, filename: "k7-dark-peru.png", origin: "Peru", roast: "dark", notes: ["Smoky", "Apple", "Mint"] },
  { name: "Villa Sarchi", price: 22.88, rating: 9, weight: 22, filename: "villa-sarchi-light-costa-rica.png", origin: "Costa Rica", roast: "light", notes: ["Molasses", "Berry"] },
  { name: "Sudan Rume", price: 21.28, rating: 4, weight: 16, filename: "sudan-rume-light-india.png", origin: "India", roast: "light", notes: ["Clove", "Dark chocolate"] },
  { name: "Maracaturra", price: 6.66, rating: 5, weight: 6, filename: "maracaturra-light-honduras.png", origin: "Honduras", roast: "light", notes: ["Cardamom", "Lavender"] },
  { name: "Red Bourbon", price: 34.98, rating: 2, weight: 22, filename: "red-bourbon-medium-peru.png", origin: "Peru", roast: "medium", notes: ["Earthy", "Woody"] },
  { name: "Red Catuai", price: 6.86, rating: 8, weight: 7, filename: "red-catuai-light-vietnam.png", origin: "Vietnam", roast: "light", notes: ["Apricot", "Hibiscus", "Tobacco"] },
  { name: "Java", price: 5.16, rating: 7, weight: 6, filename: "java-medium-tanzania.png", origin: "Tanzania", roast: "medium", notes: ["Raisin", "Milk chocolate"] },
  { name: "Pacas", price: 25.74, rating: 9, weight: 18, filename: "pacas-dark-tanzania.png", origin: "Tanzania", roast: "dark", notes: ["Cardamom", "Caramel", "Orange blossom"] },
  { name: "Yellow Catuai", price: 12.54, rating: 6, weight: 22, filename: "yellow-catuai-dark-colombia.png", origin: "Colombia", roast: "dark", notes: ["Citrus", "Clove"] },
  { name: "Parainema", price: 35.52, rating: 2, weight: 32, filename: "parainema-medium-india.png", origin: "India", roast: "medium", notes: ["Milk chocolate", "Brown sugar"] },
  { name: "Gesha", price: 10.25, rating: 10, weight: 25, filename: "gesha-medium-vietnam.png", origin: "Vietnam", roast: "medium", notes: ["Walnut", "Molasses"] },
  { name: "S795", price: 37.0, rating: 6, weight: 25, filename: "s795-dark-costa-rica.png", origin: "Costa Rica", roast: "dark", notes: ["Vanilla", "Apricot", "Tobacco"] },
  {
    name: "Blue Mountain Typica",
    price: 12.78,
    rating: 4,
    weight: 18,
    filename: "blue-mountain-typica-medium-india.png",
    origin: "India",
    roast: "medium",
    notes: ["Caramel", "Cardamom"],
  },
  {
    name: "Hibrido de Timor",
    price: 10.72,
    rating: 4,
    weight: 16,
    filename: "hibrido-de-timor-dark-kenya.png",
    origin: "Kenya",
    roast: "dark",
    notes: ["Maple syrup", "Apricot", "Raisin"],
  },
  { name: "Catuai Rojo", price: 47.04, rating: 2, weight: 32, filename: "catuai-rojo-light-kenya.png", origin: "Kenya", roast: "light", notes: ["Malt", "Lavender", "Rose"] },
  {
    name: "Yellow Icatu",
    price: 14.19,
    rating: 2,
    weight: 11,
    filename: "yellow-icatu-dark-honduras.png",
    origin: "Honduras",
    roast: "dark",
    notes: ["Apple", "Milk chocolate", "Vanilla"],
  },
  { name: "Marsellesa", price: 7.56, rating: 2, weight: 6, filename: "marsellesa-dark-brazil.png", origin: "Brazil", roast: "dark", notes: ["Hibiscus", "Apricot", "Caramel"] },
  { name: "Bourbon Mayaguez", price: 9.48, rating: 10, weight: 6, filename: "bourbon-mayaguez-light-india.png", origin: "India", roast: "light", notes: ["Almond", "Caramel"] },
  {
    name: "Catua\u00ed Amarelo",
    price: 7.2,
    rating: 4,
    weight: 6,
    filename: "catuai-amarelo-medium-tanzania.png",
    origin: "Tanzania",
    roast: "medium",
    notes: ["Maple syrup", "Woody"],
  },
  { name: "Catua\u00ed Vermelho", price: 19.14, rating: 3, weight: 22, filename: "catuai-vermelho-light-yemen.png", origin: "Yemen", roast: "light", notes: ["Tobacco", "Walnut"] },
  {
    name: "Kianjiru",
    price: 20.8,
    rating: 10,
    weight: 32,
    filename: "kianjiru-light-costa-rica.png",
    origin: "Costa Rica",
    roast: "light",
    notes: ["Cinnamon", "Brown sugar", "Molasses"],
  },
  { name: "Bourbon Sidama", price: 28.82, rating: 6, weight: 22, filename: "bourbon-sidama-dark-india.png", origin: "India", roast: "dark", notes: ["Apple", "Black pepper"] },
  {
    name: "Red Maragogipe",
    price: 3.22,
    rating: 7,
    weight: 7,
    filename: "red-maragogipe-light-colombia.png",
    origin: "Colombia",
    roast: "light",
    notes: ["Molasses", "Caramel", "Orange blossom"],
  },
  {
    name: "Yellow Maragogipe",
    price: 10.36,
    rating: 10,
    weight: 7,
    filename: "yellow-maragogipe-medium-ethiopia.png",
    origin: "Ethiopia",
    roast: "medium",
    notes: ["Maple syrup", "Honey"],
  },
  { name: "Colombia", price: 16.72, rating: 9, weight: 11, filename: "colombia-medium-yemen.png", origin: "Yemen", roast: "medium", notes: ["Cherry", "Nutmeg", "Dark chocolate"] },
  { name: "Tabi", price: 20.0, rating: 7, weight: 16, filename: "tabi-medium-costa-rica.png", origin: "Costa Rica", roast: "medium", notes: ["Basil", "Milk chocolate"] },
  { name: "Catigua", price: 12.98, rating: 3, weight: 22, filename: "catigua-dark-brazil.png", origin: "Brazil", roast: "dark", notes: ["Thyme", "Raisin"] },
  { name: "Pacamara", price: 50.56, rating: 9, weight: 32, filename: "pacamara-medium-india.png", origin: "India", roast: "medium", notes: ["Mint", "Apple"] },
  { name: "Obata Amarelo", price: 17.6, rating: 2, weight: 22, filename: "obata-amarelo-medium-vietnam.png", origin: "Vietnam", roast: "medium", notes: ["Thyme", "Dark chocolate"] },
  {
    name: "Obata Vermelho",
    price: 24.12,
    rating: 8,
    weight: 18,
    filename: "obata-vermelho-light-colombia.png",
    origin: "Colombia",
    roast: "light",
    notes: ["Clove", "Walnut", "Orange blossom"],
  },
  { name: "IAC 125 RN", price: 4.69, rating: 4, weight: 7, filename: "iac-125-rn-medium-tanzania.png", origin: "Tanzania", roast: "medium", notes: ["Molasses", "Apple"] },
  { name: "IAC 1057", price: 24.42, rating: 9, weight: 22, filename: "iac-1057-medium-kenya.png", origin: "Kenya", roast: "medium", notes: ["Jasmine", "Walnut", "Maple syrup"] },
  { name: "Obat\u00e3", price: 5.5, rating: 4, weight: 11, filename: "obata-light-ethiopia.png", origin: "Ethiopia", roast: "light", notes: ["Brown sugar", "Earthy", "Smoky"] },
  { name: "Oro Azteca", price: 26.82, rating: 8, weight: 18, filename: "oro-azteca-dark-costa-rica.png", origin: "Costa Rica", roast: "dark", notes: ["Malt", "Lavender"] },
  { name: "Sachimor", price: 7.02, rating: 5, weight: 6, filename: "sachimor-dark-ethiopia.png", origin: "Ethiopia", roast: "dark", notes: ["Hibiscus", "Hazelnut", "Thyme"] },
  { name: "Villa Franca", price: 37.25, rating: 10, weight: 25, filename: "villa-franca-medium-peru.png", origin: "Peru", roast: "medium", notes: ["Almond", "Cocoa", "Apricot"] },
  { name: "Mundo Maya", price: 21.25, rating: 9, weight: 25, filename: "mundo-maya-medium-uganda.png", origin: "Uganda", roast: "medium", notes: ["Woody", "Hibiscus", "Smoky"] },
  { name: "Purpuracea", price: 7.02, rating: 7, weight: 6, filename: "purpuracea-dark-vietnam.png", origin: "Vietnam", roast: "dark", notes: ["Honey", "Jasmine", "Smoky"] },
  { name: "Purpurascens", price: 7.84, rating: 3, weight: 16, filename: "purpurascens-light-yemen.png", origin: "Yemen", roast: "light", notes: ["Citrus", "Thyme"] },
  {
    name: "Bourbon Mayaguez 139",
    price: 8.58,
    rating: 6,
    weight: 11,
    filename: "bourbon-mayaguez-139-light-tanzania.png",
    origin: "Tanzania",
    roast: "light",
    notes: ["Almond", "Basil"],
  },
  { name: "CR-95", price: 23.4, rating: 10, weight: 18, filename: "cr-95-medium-guatemala.png", origin: "Guatemala", roast: "medium", notes: ["Jasmine", "Milk chocolate"] },
  { name: "Lempira", price: 12.54, rating: 10, weight: 22, filename: "lempira-dark-uganda.png", origin: "Uganda", roast: "dark", notes: ["Earthy", "Hibiscus"] },
  { name: "Mandheling", price: 35.2, rating: 3, weight: 22, filename: "mandheling-dark-brazil.png", origin: "Brazil", roast: "dark", notes: ["Almond", "Cocoa"] },
  { name: "Timor Hybrid", price: 22.08, rating: 4, weight: 16, filename: "timor-hybrid-medium-yemen.png", origin: "Yemen", roast: "medium", notes: ["Cashew", "Plum"] },
  { name: "Stenophylla", price: 9.17, rating: 4, weight: 7, filename: "stenophylla-light-honduras.png", origin: "Honduras", roast: "light", notes: ["Cherry", "Rose"] },
  { name: "Villalobos Bourbon", price: 3.99, rating: 6, weight: 7, filename: "villalobos-bourbon-light-colombia.png", origin: "Colombia", roast: "light", notes: ["Tobacco", "Plum"] },
  {
    name: "Columbia Hybrid",
    price: 48.32,
    rating: 7,
    weight: 32,
    filename: "columbia-hybrid-dark-india.png",
    origin: "India",
    roast: "dark",
    notes: ["Plum", "Dark chocolate", "Jasmine"],
  },
  { name: "Red Bourbon", price: 17.6, rating: 3, weight: 11, filename: "red-bourbon-dark-kenya.png", origin: "Kenya", roast: "dark", notes: ["Apricot", "Smoky", "Peach"] },
  { name: "Blue Bourbon", price: 9.57, rating: 5, weight: 11, filename: "blue-bourbon-dark-kenya.png", origin: "Kenya", roast: "dark", notes: ["Milk chocolate", "Apricot"] },
  { name: "Bronze Bourbon", price: 5.28, rating: 10, weight: 11, filename: "bronze-bourbon-dark-kenya.png", origin: "Kenya", roast: "dark", notes: ["Cashew", "Cardamom"] },
  {
    name: "Castillo Tambo",
    price: 32.78,
    rating: 5,
    weight: 22,
    filename: "castillo-tambo-medium-colombia.png",
    origin: "Colombia",
    roast: "medium",
    notes: ["Honey", "Dark chocolate", "Raisin"],
  },
  { name: "Castillo Paraguaicito", price: 32.25, rating: 2, weight: 25, filename: "castillo-paraguaicito-light-peru.png", origin: "Peru", roast: "light", notes: ["Malt", "Raisin"] },
  { name: "Castillo El Tambo", price: 24.66, rating: 10, weight: 18, filename: "castillo-el-tambo-dark-brazil.png", origin: "Brazil", roast: "dark", notes: ["Raisin", "Thyme"] },
  {
    name: "Castillo Naranjal",
    price: 29.26,
    rating: 5,
    weight: 22,
    filename: "castillo-naranjal-dark-indonesia.png",
    origin: "Indonesia",
    roast: "dark",
    notes: ["Milk chocolate", "Berry", "Hibiscus"],
  },
  {
    name: "Castillo Mesopotamia",
    price: 8.64,
    rating: 8,
    weight: 6,
    filename: "castillo-mesopotamia-dark-costa-rica.png",
    origin: "Costa Rica",
    roast: "dark",
    notes: ["Apricot", "Mint", "Caramel"],
  },
  { name: "Castillo Cauca", price: 27.9, rating: 9, weight: 18, filename: "castillo-cauca-medium-vietnam.png", origin: "Vietnam", roast: "medium", notes: ["Malt", "Almond"] },
  { name: "Castillo Timor", price: 5.28, rating: 9, weight: 11, filename: "castillo-timor-light-uganda.png", origin: "Uganda", roast: "light", notes: ["Nutmeg", "Almond"] },
  {
    name: "Sarchimor Hybrid",
    price: 8.47,
    rating: 9,
    weight: 7,
    filename: "sarchimor-hybrid-medium-tanzania.png",
    origin: "Tanzania",
    roast: "medium",
    notes: ["Clove", "Citrus", "Earthy"],
  },
  {
    name: "Catuca\u00ed",
    price: 6.27,
    rating: 9,
    weight: 11,
    filename: "catucai-medium-tanzania.png",
    origin: "Tanzania",
    roast: "medium",
    notes: ["Dark chocolate", "Jasmine", "Caramel"],
  },
  {
    name: "Colombia Supremo",
    price: 4.08,
    rating: 7,
    weight: 6,
    filename: "colombia-supremo-medium-brazil.png",
    origin: "Brazil",
    roast: "medium",
    notes: ["Rose", "Dark chocolate", "Cherry"],
  },
  { name: "Santos", price: 29.12, rating: 6, weight: 32, filename: "santos-medium-uganda.png", origin: "Uganda", roast: "medium", notes: ["Milk chocolate", "Tobacco"] },
  { name: "Bourbon Rey", price: 14.72, rating: 6, weight: 16, filename: "bourbon-rey-dark-peru.png", origin: "Peru", roast: "dark", notes: ["Earthy", "Vanilla", "Cardamom"] },
  { name: "Maracas", price: 19.58, rating: 8, weight: 22, filename: "maracas-medium-india.png", origin: "India", roast: "medium", notes: ["Honey", "Rose"] },
  { name: "Catu\u00edca", price: 7.44, rating: 8, weight: 6, filename: "catuica-dark-yemen.png", origin: "Yemen", roast: "dark", notes: ["Raisin", "Basil"] },
  { name: "Java Blue", price: 33.22, rating: 8, weight: 22, filename: "java-blue-light-tanzania.png", origin: "Tanzania", roast: "light", notes: ["Cardamom", "Apricot"] },
  { name: "Centroamericano", price: 43.84, rating: 4, weight: 32, filename: "centroamericano-dark-yemen.png", origin: "Yemen", roast: "dark", notes: ["Apple", "Walnut"] },
  {
    name: "Robusta Laurina",
    price: 48.96,
    rating: 5,
    weight: 32,
    filename: "robusta-laurina-medium-brazil.png",
    origin: "Brazil",
    roast: "medium",
    notes: ["Tobacco", "Almond", "Citrus"],
  },
  {
    name: "Robusta Monsoon",
    price: 32.78,
    rating: 3,
    weight: 22,
    filename: "robusta-monsoon-light-ethiopia.png",
    origin: "Ethiopia",
    roast: "light",
    notes: ["Citrus", "Cinnamon", "Cardamom"],
  },
  { name: "Asprotimana", price: 13.64, rating: 3, weight: 11, filename: "asprotimana-medium-india.png", origin: "India", roast: "medium", notes: ["Basil", "Walnut"] },
  {
    name: "Java Boliviana",
    price: 37.25,
    rating: 8,
    weight: 25,
    filename: "java-boliviana-dark-honduras.png",
    origin: "Honduras",
    roast: "dark",
    notes: ["Black pepper", "Molasses", "Citrus"],
  },
  { name: "Mundo Maya", price: 10.12, rating: 2, weight: 22, filename: "mundo-maya-dark-indonesia.png", origin: "Indonesia", roast: "dark", notes: ["Basil", "Rose"] },
  {
    name: "Obat\u00e3 Robusta",
    price: 22.4,
    rating: 2,
    weight: 32,
    filename: "obata-robusta-light-yemen.png",
    origin: "Yemen",
    roast: "light",
    notes: ["Apricot", "Brown sugar", "Milk chocolate"],
  },
  { name: "Paraiso", price: 5.6, rating: 6, weight: 7, filename: "paraiso-dark-peru.png", origin: "Peru", roast: "dark", notes: ["Hazelnut", "Black pepper", "Cocoa"] },
  {
    name: "Heirloom Ethiopian",
    price: 29.04,
    rating: 9,
    weight: 22,
    filename: "heirloom-ethiopian-light-yemen.png",
    origin: "Yemen",
    roast: "light",
    notes: ["Raisin", "Cashew", "Honey"],
  },
  { name: "Tekisik", price: 34.25, rating: 3, weight: 25, filename: "tekisik-light-brazil.png", origin: "Brazil", roast: "light", notes: ["Cinnamon", "Raisin"] },
  { name: "Mibiruca", price: 3.3, rating: 6, weight: 6, filename: "mibiruca-light-colombia.png", origin: "Colombia", roast: "light", notes: ["Lavender", "Cocoa"] },
  { name: "Kamwangi", price: 6.3, rating: 7, weight: 7, filename: "kamwangi-light-uganda.png", origin: "Uganda", roast: "light", notes: ["Citrus", "Clove"] },
  {
    name: "Yellow Pacamara",
    price: 38.4,
    rating: 6,
    weight: 32,
    filename: "yellow-pacamara-light-uganda.png",
    origin: "Uganda",
    roast: "light",
    notes: ["Milk chocolate", "Orange blossom"],
  },
  { name: "Kaku", price: 14.25, rating: 9, weight: 25, filename: "kaku-dark-vietnam.png", origin: "Vietnam", roast: "dark", notes: ["Cinnamon", "Berry", "Black pepper"] },
  { name: "Palaroni", price: 36.16, rating: 3, weight: 32, filename: "palaroni-medium-vietnam.png", origin: "Vietnam", roast: "medium", notes: ["Tobacco", "Milk chocolate"] },
  { name: "BM-139", price: 6.3, rating: 4, weight: 6, filename: "bm-139-light-yemen.png", origin: "Yemen", roast: "light", notes: ["Smoky", "Vanilla"] },
  { name: "Kaveka", price: 6.3, rating: 3, weight: 6, filename: "kaveka-light-kenya.png", origin: "Kenya", roast: "light", notes: ["Malt", "Raisin", "Milk chocolate"] },
  { name: "Parana", price: 4.2, rating: 10, weight: 7, filename: "parana-light-ethiopia.png", origin: "Ethiopia", roast: "light", notes: ["Maple syrup", "Tobacco", "Nutmeg"] },
  { name: "Riachuelo", price: 22.24, rating: 5, weight: 16, filename: "riachuelo-light-indonesia.png", origin: "Indonesia", roast: "light", notes: ["Earthy", "Woody"] },
  { name: "Puerbaron", price: 17.16, rating: 2, weight: 22, filename: "puerbaron-medium-yemen.png", origin: "Yemen", roast: "medium", notes: ["Peach", "Maple syrup", "Woody"] },
  { name: "IAPAR 59", price: 31.04, rating: 4, weight: 32, filename: "iapar-59-light-costa-rica.png", origin: "Costa Rica", roast: "light", notes: ["Nutmeg", "Rose"] },
  { name: "Jacu Bird", price: 16.96, rating: 10, weight: 32, filename: "jacu-bird-medium-yemen.png", origin: "Yemen", roast: "medium", notes: ["Smoky", "Lavender", "Brown sugar"] },
  { name: "Ruiru", price: 15.66, rating: 2, weight: 18, filename: "ruiru-light-guatemala.png", origin: "Guatemala", roast: "light", notes: ["Cashew", "Black pepper"] },
];
