interface Coffee {
  rating: number;
  name: string;
  roast: string;
  origin: string;
  filename: string;
  notes: string[];
  price: number;
  weight: number;
}

export const Coffees: Coffee[] = [
  { name: "Arabica", price: 17.44, rating: 5, weight: 16, filename: "arabica-light-india.png", origin: "India", roast: "light", notes: ["Hazelnut", "Sage", "Milk chocolate"] },
  { name: "Robusta", price: 38.4, rating: 9, weight: 32, filename: "robusta-dark-uganda.png", origin: "Uganda", roast: "dark", notes: ["Plum", "Hibiscus", "Apple"] },
  { name: "Bourbon", price: 28.16, rating: 8, weight: 22, filename: "bourbon-medium-yemen.png", origin: "Yemen", roast: "medium", notes: ["Dark chocolate", "Apricot"] },
  { name: "Typica", price: 7.21, rating: 5, weight: 7, filename: "typica-light-uganda.png", origin: "Uganda", roast: "light", notes: ["Hibiscus", "Caramel"] },
  { name: "Geisha", price: 28.08, rating: 9, weight: 18, filename: "geisha-light-kenya.png", origin: "Kenya", roast: "light", notes: ["Sage", "Hibiscus", "Rose"] },
  { name: "Catuai", price: 5.88, rating: 8, weight: 7, filename: "catuai-medium-kenya.png", origin: "Kenya", roast: "medium", notes: ["Malt", "Thyme"] },
  { name: "SL28", price: 9.68, rating: 9, weight: 11, filename: "sl28-light-peru.png", origin: "Peru", roast: "light", notes: ["Dark chocolate", "Sage"] },
  { name: "SL34", price: 28.26, rating: 10, weight: 18, filename: "sl34-light-honduras.png", origin: "Honduras", roast: "light", notes: ["Mint", "Dark chocolate", "Maple syrup"] },
  { name: "Pacamara", price: 8.16, rating: 9, weight: 16, filename: "pacamara-light-kenya.png", origin: "Kenya", roast: "light", notes: ["Berry", "Brown sugar"] },
  {
    name: "Maragogipe",
    price: 37.44,
    rating: 7,
    weight: 32,
    filename: "maragogipe-medium-guatemala.png",
    origin: "Guatemala",
    roast: "medium",
    notes: ["Apricot", "Earthy", "Jasmine"],
  },
  { name: "Caturra", price: 16.0, rating: 8, weight: 25, filename: "caturra-light-tanzania.png", origin: "Tanzania", roast: "light", notes: ["Earthy", "Cashew"] },
  { name: "Castillo", price: 45.44, rating: 4, weight: 32, filename: "castillo-dark-peru.png", origin: "Peru", roast: "dark", notes: ["Apricot", "Peach"] },
  { name: "Catimor", price: 13.86, rating: 5, weight: 11, filename: "catimor-dark-uganda.png", origin: "Uganda", roast: "dark", notes: ["Mint", "Clove", "Raisin"] },
  { name: "Ruiru 11", price: 16.25, rating: 7, weight: 25, filename: "ruiru-11-light-honduras.png", origin: "Honduras", roast: "light", notes: ["Lavender", "Honey", "Hazelnut"] },
  { name: "Villalobos", price: 3.36, rating: 7, weight: 6, filename: "villalobos-light-kenya.png", origin: "Kenya", roast: "light", notes: ["Apple", "Cashew"] },
  { name: "Mokka", price: 18.75, rating: 6, weight: 25, filename: "mokka-medium-costa-rica.png", origin: "Costa Rica", roast: "medium", notes: ["Cocoa", "Rose"] },
  {
    name: "Mundo Novo",
    price: 46.72,
    rating: 8,
    weight: 32,
    filename: "mundo-novo-medium-colombia.png",
    origin: "Colombia",
    roast: "medium",
    notes: ["Hazelnut", "Cherry", "Molasses"],
  },
  { name: "Blue Mountain", price: 50.88, rating: 6, weight: 32, filename: "blue-mountain-medium-brazil.png", origin: "Brazil", roast: "medium", notes: ["Apricot", "Brown sugar"] },
  { name: "Kona", price: 10.85, rating: 2, weight: 7, filename: "kona-medium-ethiopia.png", origin: "Ethiopia", roast: "medium", notes: ["Honey", "Dark chocolate", "Hazelnut"] },
  { name: "Laurina", price: 17.76, rating: 8, weight: 16, filename: "laurina-light-uganda.png", origin: "Uganda", roast: "light", notes: ["Cocoa", "Cardamom", "Hazelnut"] },
  { name: "Obata", price: 20.25, rating: 6, weight: 25, filename: "obata-medium-guatemala.png", origin: "Guatemala", roast: "medium", notes: ["Earthy", "Walnut", "Honey"] },
  { name: "Icatu", price: 12.98, rating: 2, weight: 22, filename: "icatu-medium-peru.png", origin: "Peru", roast: "medium", notes: ["Malt", "Cherry", "Walnut"] },
  { name: "San Ramon", price: 16.94, rating: 10, weight: 22, filename: "san-ramon-light-kenya.png", origin: "Kenya", roast: "light", notes: ["Cocoa", "Black pepper"] },
  { name: "Pache", price: 11.22, rating: 3, weight: 22, filename: "pache-light-india.png", origin: "India", roast: "light", notes: ["Rose", "Berry", "Nutmeg"] },
  { name: "Sarchimor", price: 16.2, rating: 6, weight: 18, filename: "sarchimor-dark-honduras.png", origin: "Honduras", roast: "dark", notes: ["Hibiscus", "Black pepper"] },
  { name: "Amarello", price: 25.74, rating: 3, weight: 18, filename: "amarello-medium-honduras.png", origin: "Honduras", roast: "medium", notes: ["Black pepper", "Vanilla"] },
  { name: "Bourbon Pointu", price: 5.22, rating: 10, weight: 6, filename: "bourbon-pointu-light-kenya.png", origin: "Kenya", roast: "light", notes: ["Hazelnut", "Cinnamon", "Clove"] },
  {
    name: "Orange Bourbon",
    price: 25.25,
    rating: 6,
    weight: 25,
    filename: "orange-bourbon-dark-tanzania.png",
    origin: "Tanzania",
    roast: "dark",
    notes: ["Earthy", "Thyme", "Brown sugar"],
  },
  { name: "Jackson", price: 6.78, rating: 6, weight: 6, filename: "jackson-medium-honduras.png", origin: "Honduras", roast: "medium", notes: ["Almond", "Lavender"] },
  { name: "Batian", price: 4.02, rating: 3, weight: 6, filename: "batian-light-honduras.png", origin: "Honduras", roast: "light", notes: ["Jasmine", "Black pepper"] },
  { name: "Yellow Bourbon", price: 16.0, rating: 4, weight: 25, filename: "yellow-bourbon-medium-india.png", origin: "India", roast: "medium", notes: ["Sage", "Cocoa", "Molasses"] },
  { name: "Pink Bourbon", price: 7.56, rating: 6, weight: 6, filename: "pink-bourbon-dark-costa-rica.png", origin: "Costa Rica", roast: "dark", notes: ["Sage", "Berry", "Smoky"] },
  { name: "K7", price: 26.64, rating: 9, weight: 18, filename: "k7-dark-yemen.png", origin: "Yemen", roast: "dark", notes: ["Brown sugar", "Cherry", "Walnut"] },
  { name: "Villa Sarchi", price: 9.24, rating: 4, weight: 11, filename: "villa-sarchi-medium-guatemala.png", origin: "Guatemala", roast: "medium", notes: ["Hibiscus", "Cinnamon"] },
  { name: "Sudan Rume", price: 6.88, rating: 4, weight: 16, filename: "sudan-rume-dark-vietnam.png", origin: "Vietnam", roast: "dark", notes: ["Plum", "Clove"] },
  { name: "Maracaturra", price: 4.44, rating: 6, weight: 6, filename: "maracaturra-medium-yemen.png", origin: "Yemen", roast: "medium", notes: ["Cinnamon", "Cashew", "Citrus"] },
  {
    name: "Red Bourbon",
    price: 22.86,
    rating: 3,
    weight: 18,
    filename: "red-bourbon-medium-tanzania.png",
    origin: "Tanzania",
    roast: "medium",
    notes: ["Caramel", "Cashew", "Milk chocolate"],
  },
  { name: "Red Catuai", price: 37.75, rating: 5, weight: 25, filename: "red-catuai-medium-brazil.png", origin: "Brazil", roast: "medium", notes: ["Walnut", "Vanilla"] },
  { name: "Java", price: 6.18, rating: 4, weight: 6, filename: "java-light-ethiopia.png", origin: "Ethiopia", roast: "light", notes: ["Black pepper", "Orange blossom", "Basil"] },
  { name: "Pacas", price: 7.21, rating: 6, weight: 7, filename: "pacas-light-colombia.png", origin: "Colombia", roast: "light", notes: ["Orange blossom", "Woody"] },
  {
    name: "Yellow Catuai",
    price: 17.16,
    rating: 6,
    weight: 22,
    filename: "yellow-catuai-medium-ethiopia.png",
    origin: "Ethiopia",
    roast: "medium",
    notes: ["Smoky", "Tobacco", "Cashew"],
  },
  { name: "Parainema", price: 15.4, rating: 7, weight: 22, filename: "parainema-light-uganda.png", origin: "Uganda", roast: "light", notes: ["Cocoa", "Hazelnut"] },
  { name: "Gesha", price: 8.16, rating: 3, weight: 6, filename: "gesha-light-peru.png", origin: "Peru", roast: "light", notes: ["Vanilla", "Tobacco", "Black pepper"] },
  { name: "S795", price: 9.6, rating: 5, weight: 6, filename: "s795-light-indonesia.png", origin: "Indonesia", roast: "light", notes: ["Plum", "Sage", "Apple"] },
  {
    name: "Blue Mountain Typica",
    price: 7.04,
    rating: 3,
    weight: 11,
    filename: "blue-mountain-typica-medium-india.png",
    origin: "India",
    roast: "medium",
    notes: ["Molasses", "Jasmine", "Smoky"],
  },
  {
    name: "Hibrido de Timor",
    price: 32.96,
    rating: 3,
    weight: 32,
    filename: "hibrido-de-timor-dark-kenya.png",
    origin: "Kenya",
    roast: "dark",
    notes: ["Woody", "Milk chocolate", "Almond"],
  },
  { name: "Catuai Rojo", price: 15.68, rating: 2, weight: 32, filename: "catuai-rojo-light-india.png", origin: "India", roast: "light", notes: ["Apple", "Earthy", "Jasmine"] },
  { name: "Yellow Icatu", price: 21.6, rating: 9, weight: 18, filename: "yellow-icatu-dark-tanzania.png", origin: "Tanzania", roast: "dark", notes: ["Walnut", "Earthy"] },
  { name: "Marsellesa", price: 8.69, rating: 6, weight: 11, filename: "marsellesa-light-honduras.png", origin: "Honduras", roast: "light", notes: ["Lavender", "Maple syrup"] },
  { name: "Bourbon Mayaguez", price: 7.2, rating: 10, weight: 16, filename: "bourbon-mayaguez-dark-kenya.png", origin: "Kenya", roast: "dark", notes: ["Cashew", "Vanilla"] },
  { name: "Catua\u00ed Amarelo", price: 7.08, rating: 9, weight: 6, filename: "catua\u00ed-amarelo-light-vietnam.png", origin: "Vietnam", roast: "light", notes: ["Almond", "Nutmeg"] },
  { name: "Catua\u00ed Vermelho", price: 14.88, rating: 10, weight: 16, filename: "catua\u00ed-vermelho-dark-uganda.png", origin: "Uganda", roast: "dark", notes: ["Peach", "Smoky"] },
  { name: "Kianjiru", price: 30.4, rating: 8, weight: 32, filename: "kianjiru-light-guatemala.png", origin: "Guatemala", roast: "light", notes: ["Almond", "Black pepper"] },
  { name: "Bourbon Sidama", price: 8.8, rating: 9, weight: 16, filename: "bourbon-sidama-medium-honduras.png", origin: "Honduras", roast: "medium", notes: ["Cardamom", "Cashew"] },
  { name: "Red Maragogipe", price: 6.05, rating: 10, weight: 11, filename: "red-maragogipe-medium-vietnam.png", origin: "Vietnam", roast: "medium", notes: ["Sage", "Citrus"] },
  {
    name: "Yellow Maragogipe",
    price: 15.07,
    rating: 2,
    weight: 11,
    filename: "yellow-maragogipe-light-guatemala.png",
    origin: "Guatemala",
    roast: "light",
    notes: ["Brown sugar", "Plum"],
  },
  {
    name: "Colombia",
    price: 6.51,
    rating: 4,
    weight: 7,
    filename: "colombia-medium-colombia.png",
    origin: "Colombia",
    roast: "medium",
    notes: ["Black pepper", "Maple syrup", "Cardamom"],
  },
  { name: "Tabi", price: 34.98, rating: 6, weight: 22, filename: "tabi-light-vietnam.png", origin: "Vietnam", roast: "light", notes: ["Cherry", "Walnut"] },
  { name: "Catigua", price: 37.75, rating: 7, weight: 25, filename: "catigua-light-uganda.png", origin: "Uganda", roast: "light", notes: ["Plum", "Clove", "Smoky"] },
  { name: "Pacamara", price: 24.2, rating: 3, weight: 22, filename: "pacamara-light-colombia.png", origin: "Colombia", roast: "light", notes: ["Cocoa", "Hazelnut"] },
  { name: "Obata Amarelo", price: 34.88, rating: 9, weight: 32, filename: "obata-amarelo-dark-kenya.png", origin: "Kenya", roast: "dark", notes: ["Berry", "Hazelnut"] },
  {
    name: "Obata Vermelho",
    price: 36.0,
    rating: 8,
    weight: 25,
    filename: "obata-vermelho-dark-honduras.png",
    origin: "Honduras",
    roast: "dark",
    notes: ["Black pepper", "Berry", "Thyme"],
  },
  { name: "IAC 125 RN", price: 3.92, rating: 2, weight: 7, filename: "iac-125-rn-medium-tanzania.png", origin: "Tanzania", roast: "medium", notes: ["Rose", "Lavender", "Hibiscus"] },
  { name: "IAC 1057", price: 17.25, rating: 2, weight: 25, filename: "iac-1057-medium-brazil.png", origin: "Brazil", roast: "medium", notes: ["Thyme", "Tobacco", "Rose"] },
  {
    name: "Obat\u00e3",
    price: 16.96,
    rating: 2,
    weight: 32,
    filename: "obat\u00e3-light-uganda.png",
    origin: "Uganda",
    roast: "light",
    notes: ["Cinnamon", "Thyme", "Milk chocolate"],
  },
  { name: "Oro Azteca", price: 21.28, rating: 6, weight: 16, filename: "oro-azteca-dark-kenya.png", origin: "Kenya", roast: "dark", notes: ["Apple", "Jasmine"] },
  { name: "Sachimor", price: 18.56, rating: 7, weight: 32, filename: "sachimor-medium-india.png", origin: "India", roast: "medium", notes: ["Cardamom", "Maple syrup", "Woody"] },
  { name: "Villa Franca", price: 15.51, rating: 6, weight: 11, filename: "villa-franca-dark-uganda.png", origin: "Uganda", roast: "dark", notes: ["Jasmine", "Cinnamon"] },
  { name: "Mundo Maya", price: 39.75, rating: 9, weight: 25, filename: "mundo-maya-dark-yemen.png", origin: "Yemen", roast: "dark", notes: ["Cardamom", "Vanilla", "Hazelnut"] },
  { name: "Purpuracea", price: 47.04, rating: 10, weight: 32, filename: "purpuracea-dark-costa-rica.png", origin: "Costa Rica", roast: "dark", notes: ["Sage", "Cinnamon"] },
  {
    name: "Purpurascens",
    price: 9.18,
    rating: 8,
    weight: 18,
    filename: "purpurascens-medium-honduras.png",
    origin: "Honduras",
    roast: "medium",
    notes: ["Tobacco", "Vanilla", "Apricot"],
  },
  {
    name: "Bourbon Mayaguez 139",
    price: 28.08,
    rating: 10,
    weight: 18,
    filename: "bourbon-mayaguez-139-medium-guatemala.png",
    origin: "Guatemala",
    roast: "medium",
    notes: ["Black pepper", "Hibiscus", "Citrus"],
  },
  { name: "CR-95", price: 14.52, rating: 10, weight: 22, filename: "cr-95-medium-vietnam.png", origin: "Vietnam", roast: "medium", notes: ["Rose", "Berry", "Hibiscus"] },
  { name: "Lempira", price: 4.69, rating: 4, weight: 7, filename: "lempira-dark-indonesia.png", origin: "Indonesia", roast: "dark", notes: ["Citrus", "Peach"] },
  { name: "Mandheling", price: 12.98, rating: 7, weight: 22, filename: "mandheling-medium-vietnam.png", origin: "Vietnam", roast: "medium", notes: ["Vanilla", "Thyme"] },
  { name: "Timor Hybrid", price: 13.14, rating: 5, weight: 18, filename: "timor-hybrid-dark-guatemala.png", origin: "Guatemala", roast: "dark", notes: ["Apple", "Berry"] },
  { name: "Stenophylla", price: 19.36, rating: 7, weight: 22, filename: "stenophylla-dark-vietnam.png", origin: "Vietnam", roast: "dark", notes: ["Basil", "Black pepper"] },
  { name: "Villalobos Bourbon", price: 11.13, rating: 5, weight: 7, filename: "villalobos-bourbon-dark-peru.png", origin: "Peru", roast: "dark", notes: ["Dark chocolate", "Rose"] },
  {
    name: "Columbia Hybrid",
    price: 27.28,
    rating: 2,
    weight: 22,
    filename: "columbia-hybrid-dark-honduras.png",
    origin: "Honduras",
    roast: "dark",
    notes: ["Raisin", "Plum", "Cocoa"],
  },
  { name: "Red Bourbon", price: 17.49, rating: 10, weight: 11, filename: "red-bourbon-medium-india.png", origin: "India", roast: "medium", notes: ["Citrus", "Nutmeg", "Walnut"] },
  {
    name: "Blue Bourbon",
    price: 19.0,
    rating: 4,
    weight: 25,
    filename: "blue-bourbon-light-ethiopia.png",
    origin: "Ethiopia",
    roast: "light",
    notes: ["Apricot", "Basil", "Dark chocolate"],
  },
  { name: "Bronze Bourbon", price: 6.54, rating: 2, weight: 6, filename: "bronze-bourbon-medium-vietnam.png", origin: "Vietnam", roast: "medium", notes: ["Peach", "Clove", "Plum"] },
  {
    name: "Castillo Tambo",
    price: 5.06,
    rating: 9,
    weight: 11,
    filename: "castillo-tambo-light-costa-rica.png",
    origin: "Costa Rica",
    roast: "light",
    notes: ["Apricot", "Raisin", "Hibiscus"],
  },
  { name: "Castillo Paraguaicito", price: 9.6, rating: 8, weight: 16, filename: "castillo-paraguaicito-dark-brazil.png", origin: "Brazil", roast: "dark", notes: ["Plum", "Basil"] },
  {
    name: "Castillo El Tambo",
    price: 29.26,
    rating: 4,
    weight: 22,
    filename: "castillo-el-tambo-dark-guatemala.png",
    origin: "Guatemala",
    roast: "dark",
    notes: ["Cardamom", "Molasses"],
  },
  {
    name: "Castillo Naranjal",
    price: 12.8,
    rating: 3,
    weight: 16,
    filename: "castillo-naranjal-dark-guatemala.png",
    origin: "Guatemala",
    roast: "dark",
    notes: ["Citrus", "Walnut", "Berry"],
  },
  {
    name: "Castillo Mesopotamia",
    price: 15.62,
    rating: 3,
    weight: 11,
    filename: "castillo-mesopotamia-medium-colombia.png",
    origin: "Colombia",
    roast: "medium",
    notes: ["Cashew", "Rose", "Cherry"],
  },
  {
    name: "Castillo Cauca",
    price: 26.62,
    rating: 3,
    weight: 22,
    filename: "castillo-cauca-dark-colombia.png",
    origin: "Colombia",
    roast: "dark",
    notes: ["Hazelnut", "Honey", "Earthy"],
  },
  { name: "Castillo Timor", price: 15.18, rating: 10, weight: 22, filename: "castillo-timor-dark-tanzania.png", origin: "Tanzania", roast: "dark", notes: ["Apple", "Maple syrup"] },
  { name: "Sarchimor Hybrid", price: 25.92, rating: 8, weight: 32, filename: "sarchimor-hybrid-light-vietnam.png", origin: "Vietnam", roast: "light", notes: ["Malt", "Hazelnut"] },
  { name: "Catuca\u00ed", price: 8.36, rating: 2, weight: 11, filename: "catuca\u00ed-dark-tanzania.png", origin: "Tanzania", roast: "dark", notes: ["Basil", "Milk chocolate"] },
  {
    name: "Colombia Supremo",
    price: 29.75,
    rating: 2,
    weight: 25,
    filename: "colombia-supremo-dark-india.png",
    origin: "India",
    roast: "dark",
    notes: ["Rose", "Cinnamon", "Apricot"],
  },
  { name: "Santos", price: 5.17, rating: 8, weight: 11, filename: "santos-light-tanzania.png", origin: "Tanzania", roast: "light", notes: ["Plum", "Citrus", "Brown sugar"] },
  { name: "Bourbon Rey", price: 16.06, rating: 10, weight: 11, filename: "bourbon-rey-medium-indonesia.png", origin: "Indonesia", roast: "medium", notes: ["Brown sugar", "Honey"] },
  { name: "Maracas", price: 34.88, rating: 2, weight: 32, filename: "maracas-dark-indonesia.png", origin: "Indonesia", roast: "dark", notes: ["Cinnamon", "Clove", "Cocoa"] },
  { name: "Catu\u00edca", price: 7.56, rating: 4, weight: 6, filename: "catu\u00edca-dark-peru.png", origin: "Peru", roast: "dark", notes: ["Hibiscus", "Maple syrup"] },
  { name: "Java Blue", price: 11.44, rating: 8, weight: 22, filename: "java-blue-light-ethiopia.png", origin: "Ethiopia", roast: "light", notes: ["Cherry", "Tobacco"] },
  { name: "Centroamericano", price: 24.0, rating: 8, weight: 25, filename: "centroamericano-medium-ethiopia.png", origin: "Ethiopia", roast: "medium", notes: ["Basil", "Molasses"] },
  {
    name: "Robusta Laurina",
    price: 14.96,
    rating: 2,
    weight: 22,
    filename: "robusta-laurina-light-tanzania.png",
    origin: "Tanzania",
    roast: "light",
    notes: ["Peach", "Cinnamon", "Vanilla"],
  },
  { name: "Robusta Monsoon", price: 33.25, rating: 5, weight: 25, filename: "robusta-monsoon-light-tanzania.png", origin: "Tanzania", roast: "light", notes: ["Apple", "Basil"] },
  { name: "Asprotimana", price: 14.08, rating: 3, weight: 32, filename: "asprotimana-dark-yemen.png", origin: "Yemen", roast: "dark", notes: ["Lavender", "Walnut"] },
  { name: "Java Boliviana", price: 8.16, rating: 9, weight: 16, filename: "java-boliviana-dark-costa-rica.png", origin: "Costa Rica", roast: "dark", notes: ["Nutmeg", "Citrus"] },
  { name: "Mundo Maya", price: 4.62, rating: 9, weight: 6, filename: "mundo-maya-medium-honduras.png", origin: "Honduras", roast: "medium", notes: ["Honey", "Jasmine"] },
  {
    name: "Obat\u00e3 Robusta",
    price: 8.61,
    rating: 5,
    weight: 7,
    filename: "obat\u00e3-robusta-dark-guatemala.png",
    origin: "Guatemala",
    roast: "dark",
    notes: ["Brown sugar", "Jasmine"],
  },
  { name: "Paraiso", price: 8.34, rating: 7, weight: 6, filename: "paraiso-light-india.png", origin: "India", roast: "light", notes: ["Apricot", "Almond"] },
  { name: "Heirloom Ethiopian", price: 4.02, rating: 9, weight: 6, filename: "heirloom-ethiopian-medium-peru.png", origin: "Peru", roast: "medium", notes: ["Cashew", "Tobacco"] },
  { name: "Tekisik", price: 9.76, rating: 7, weight: 16, filename: "tekisik-light-guatemala.png", origin: "Guatemala", roast: "light", notes: ["Woody", "Vanilla"] },
  { name: "Mibiruca", price: 9.68, rating: 10, weight: 11, filename: "mibiruca-light-yemen.png", origin: "Yemen", roast: "light", notes: ["Black pepper", "Caramel", "Basil"] },
  { name: "Kamwangi", price: 27.75, rating: 10, weight: 25, filename: "kamwangi-medium-uganda.png", origin: "Uganda", roast: "medium", notes: ["Clove", "Woody"] },
  {
    name: "Yellow Pacamara",
    price: 26.5,
    rating: 6,
    weight: 25,
    filename: "yellow-pacamara-dark-tanzania.png",
    origin: "Tanzania",
    roast: "dark",
    notes: ["Raisin", "Apple", "Molasses"],
  },
  { name: "Kaku", price: 11.36, rating: 6, weight: 16, filename: "kaku-light-india.png", origin: "India", roast: "light", notes: ["Basil", "Dark chocolate", "Almond"] },
  { name: "Palaroni", price: 48.96, rating: 4, weight: 32, filename: "palaroni-medium-peru.png", origin: "Peru", roast: "medium", notes: ["Basil", "Vanilla", "Raisin"] },
  { name: "BM-139", price: 48.0, rating: 2, weight: 32, filename: "bm-139-dark-guatemala.png", origin: "Guatemala", roast: "dark", notes: ["Apple", "Brown sugar", "Sage"] },
  { name: "Kaveka", price: 10.12, rating: 5, weight: 22, filename: "kaveka-dark-guatemala.png", origin: "Guatemala", roast: "dark", notes: ["Milk chocolate", "Jasmine", "Smoky"] },
  { name: "Parana", price: 7.21, rating: 5, weight: 7, filename: "parana-light-uganda.png", origin: "Uganda", roast: "light", notes: ["Apricot", "Mint", "Black pepper"] },
  { name: "Riachuelo", price: 5.28, rating: 7, weight: 6, filename: "riachuelo-dark-brazil.png", origin: "Brazil", roast: "dark", notes: ["Clove", "Jasmine", "Cocoa"] },
  { name: "Puerbaron", price: 34.32, rating: 7, weight: 22, filename: "puerbaron-medium-honduras.png", origin: "Honduras", roast: "medium", notes: ["Lavender", "Earthy", "Citrus"] },
  { name: "IAPAR 59", price: 31.75, rating: 8, weight: 25, filename: "iapar-59-light-guatemala.png", origin: "Guatemala", roast: "light", notes: ["Raisin", "Hibiscus"] },
  { name: "Jacu Bird", price: 24.96, rating: 9, weight: 32, filename: "jacu-bird-light-uganda.png", origin: "Uganda", roast: "light", notes: ["Hibiscus", "Hazelnut", "Woody"] },
  { name: "Ruiru", price: 6.58, rating: 10, weight: 7, filename: "ruiru-light-costa-rica.png", origin: "Costa Rica", roast: "light", notes: ["Smoky", "Almond"] },
];
